services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=FavFlicksDb
    ports:
      - "5432:5432"
    volumes:
      - favflicks_db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile.dev
    environment:
      # Connect to the db container
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=FavFlicksDb;Username=postgres;Password=postgres
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./favflicks_front
      dockerfile: Dockerfile.dev
    environment:
      - VITE_API_BASE_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5173:5173"
    volumes:
      - ./favflicks_front:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  favflicks_db_data:
