// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using favflicks.data;

#nullable disable

namespace favflicks.data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260313091325_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MovieTag", b =>
                {
                    b.Property<int>("MoviesId")
                        .HasColumnType("integer");

                    b.Property<int>("TagsId")
                        .HasColumnType("integer");

                    b.HasKey("MoviesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("MovieTags", (string)null);

                    b.HasData(
                        new
                        {
                            MoviesId = 1,
                            TagsId = 1
                        },
                        new
                        {
                            MoviesId = 1,
                            TagsId = 4
                        },
                        new
                        {
                            MoviesId = 2,
                            TagsId = 3
                        },
                        new
                        {
                            MoviesId = 3,
                            TagsId = 2
                        },
                        new
                        {
                            MoviesId = 4,
                            TagsId = 1
                        },
                        new
                        {
                            MoviesId = 4,
                            TagsId = 4
                        },
                        new
                        {
                            MoviesId = 5,
                            TagsId = 4
                        },
                        new
                        {
                            MoviesId = 5,
                            TagsId = 3
                        },
                        new
                        {
                            MoviesId = 6,
                            TagsId = 3
                        },
                        new
                        {
                            MoviesId = 7,
                            TagsId = 1
                        },
                        new
                        {
                            MoviesId = 7,
                            TagsId = 3
                        },
                        new
                        {
                            MoviesId = 8,
                            TagsId = 3
                        },
                        new
                        {
                            MoviesId = 9,
                            TagsId = 1
                        },
                        new
                        {
                            MoviesId = 9,
                            TagsId = 4
                        },
                        new
                        {
                            MoviesId = 10,
                            TagsId = 3
                        },
                        new
                        {
                            MoviesId = 11,
                            TagsId = 1
                        },
                        new
                        {
                            MoviesId = 11,
                            TagsId = 3
                        },
                        new
                        {
                            MoviesId = 12,
                            TagsId = 2
                        },
                        new
                        {
                            MoviesId = 12,
                            TagsId = 4
                        },
                        new
                        {
                            MoviesId = 13,
                            TagsId = 4
                        },
                        new
                        {
                            MoviesId = 13,
                            TagsId = 1
                        },
                        new
                        {
                            MoviesId = 14,
                            TagsId = 3
                        },
                        new
                        {
                            MoviesId = 15,
                            TagsId = 3
                        },
                        new
                        {
                            MoviesId = 15,
                            TagsId = 1
                        },
                        new
                        {
                            MoviesId = 16,
                            TagsId = 4
                        },
                        new
                        {
                            MoviesId = 16,
                            TagsId = 2
                        },
                        new
                        {
                            MoviesId = 17,
                            TagsId = 3
                        },
                        new
                        {
                            MoviesId = 18,
                            TagsId = 3
                        },
                        new
                        {
                            MoviesId = 19,
                            TagsId = 2
                        },
                        new
                        {
                            MoviesId = 19,
                            TagsId = 3
                        },
                        new
                        {
                            MoviesId = 20,
                            TagsId = 3
                        },
                        new
                        {
                            MoviesId = 20,
                            TagsId = 2
                        });
                });

            modelBuilder.Entity("favflicks.data.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000000",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b2c3d4e5-f6a7-8901-bcde-f12345678901",
                            Email = "defaultuser@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DEFAULTUSER@EXAMPLE.COM",
                            NormalizedUserName = "TESTUSER",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                            TwoFactorEnabled = false,
                            UserName = "testuser"
                        });
                });

            modelBuilder.Entity("favflicks.data.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("favflicks.data.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("favflicks.data.Models.ListMovie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<int>("UserListId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserListId");

                    b.ToTable("ListMovie");
                });

            modelBuilder.Entity("favflicks.data.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("BackdropPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CountryOfOrigin")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Director")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Genre")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ImdbUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Language")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProductionCompany")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RuntimeMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Stars")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Writers")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("YouTubeTrailerId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AddedByUserId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedByUserId = "00000000-0000-0000-0000-000000000000",
                            DateAdded = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A thief uses dream-sharing technology to infiltrate minds.",
                            ImagePath = "/images/movies/inception.jpg",
                            Name = "Inception",
                            Source = "UserImport"
                        },
                        new
                        {
                            Id = 2,
                            AddedByUserId = "00000000-0000-0000-0000-000000000000",
                            DateAdded = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The aging patriarch of a crime dynasty transfers control to his son.",
                            ImagePath = "/images/movies/godfather.jpg",
                            Name = "The Godfather",
                            Source = "UserImport"
                        },
                        new
                        {
                            Id = 3,
                            AddedByUserId = "00000000-0000-0000-0000-000000000000",
                            DateAdded = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Two teens navigate friendship and parties before college.",
                            ImagePath = "/images/movies/superbad.jpg",
                            Name = "Superbad",
                            Source = "UserImport"
                        },
                        new
                        {
                            Id = 4,
                            AddedByUserId = "00000000-0000-0000-0000-000000000000",
                            DateAdded = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A hacker learns about the true nature of his reality.",
                            ImagePath = "/images/movies/matrix.jpg",
                            Name = "The Matrix",
                            Source = "UserImport"
                        },
                        new
                        {
                            Id = 5,
                            AddedByUserId = "00000000-0000-0000-0000-000000000000",
                            DateAdded = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A team travels through a wormhole in space to ensure humanity's survival.",
                            ImagePath = "/images/movies/interstellar.jpg",
                            Name = "Interstellar",
                            Source = "UserImport"
                        },
                        new
                        {
                            Id = 6,
                            AddedByUserId = "00000000-0000-0000-0000-000000000000",
                            DateAdded = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The lives of criminals intertwine in this nonlinear story.",
                            ImagePath = "/images/movies/pulpfiction.jpg",
                            Name = "Pulp Fiction",
                            Source = "UserImport"
                        },
                        new
                        {
                            Id = 7,
                            AddedByUserId = "00000000-0000-0000-0000-000000000000",
                            DateAdded = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Batman faces his greatest challenge in the form of the Joker.",
                            ImagePath = "/images/movies/darkknight.jpg",
                            Name = "The Dark Knight",
                            Source = "UserImport"
                        },
                        new
                        {
                            Id = 8,
                            AddedByUserId = "00000000-0000-0000-0000-000000000000",
                            DateAdded = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A man's simple outlook leads him through incredible life events.",
                            ImagePath = "/images/movies/forrestgump.jpg",
                            Name = "Forrest Gump",
                            Source = "UserImport"
                        },
                        new
                        {
                            Id = 9,
                            AddedByUserId = "00000000-0000-0000-0000-000000000000",
                            DateAdded = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Earth's mightiest heroes must unite to save the world.",
                            ImagePath = "/images/movies/avengers.jpg",
                            Name = "The Avengers",
                            Source = "UserImport"
                        },
                        new
                        {
                            Id = 10,
                            AddedByUserId = "00000000-0000-0000-0000-000000000000",
                            DateAdded = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A romance unfolds aboard the ill-fated RMS Titanic.",
                            ImagePath = "/images/movies/titanic.jpg",
                            Name = "Titanic",
                            Source = "UserImport"
                        },
                        new
                        {
                            Id = 11,
                            AddedByUserId = "00000000-0000-0000-0000-000000000000",
                            DateAdded = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A betrayed Roman general seeks revenge.",
                            ImagePath = "/images/movies/gladiator.jpg",
                            Name = "Gladiator",
                            Source = "UserImport"
                        },
                        new
                        {
                            Id = 12,
                            AddedByUserId = "00000000-0000-0000-0000-000000000000",
                            DateAdded = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Toys come to life when humans aren't around.",
                            ImagePath = "/images/movies/toystory.jpg",
                            Name = "Toy Story",
                            Source = "UserImport"
                        },
                        new
                        {
                            Id = 13,
                            AddedByUserId = "00000000-0000-0000-0000-000000000000",
                            DateAdded = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A theme park suffers a major security breakdown with dinosaurs.",
                            ImagePath = "/images/movies/jurassicpark.jpg",
                            Name = "Jurassic Park",
                            Source = "UserImport"
                        },
                        new
                        {
                            Id = 14,
                            AddedByUserId = "00000000-0000-0000-0000-000000000000",
                            DateAdded = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Two imprisoned men bond over the years.",
                            ImagePath = "/images/movies/shawshank.jpg",
                            Name = "The Shawshank Redemption",
                            Source = "UserImport"
                        },
                        new
                        {
                            Id = 15,
                            AddedByUserId = "00000000-0000-0000-0000-000000000000",
                            DateAdded = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A lion cub's journey to reclaim his kingdom.",
                            ImagePath = "/images/movies/lionking.jpg",
                            Name = "The Lion King",
                            Source = "UserImport"
                        },
                        new
                        {
                            Id = 16,
                            AddedByUserId = "00000000-0000-0000-0000-000000000000",
                            DateAdded = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A teenager travels back in time to help his parents.",
                            ImagePath = "/images/movies/backtothefuture.jpg",
                            Name = "Back to the Future",
                            Source = "UserImport"
                        },
                        new
                        {
                            Id = 17,
                            AddedByUserId = "00000000-0000-0000-0000-000000000000",
                            DateAdded = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The story of Facebook's founding.",
                            ImagePath = "/images/movies/socialnetwork.jpg",
                            Name = "The Social Network",
                            Source = "UserImport"
                        },
                        new
                        {
                            Id = 18,
                            AddedByUserId = "00000000-0000-0000-0000-000000000000",
                            DateAdded = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "An office worker forms an underground fight club.",
                            ImagePath = "/images/movies/fightclub.jpg",
                            Name = "Fight Club",
                            Source = "UserImport"
                        },
                        new
                        {
                            Id = 19,
                            AddedByUserId = "00000000-0000-0000-0000-000000000000",
                            DateAdded = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A boy journeys to the Land of the Dead to uncover family secrets.",
                            ImagePath = "/images/movies/coco.jpg",
                            Name = "Coco",
                            Source = "UserImport"
                        },
                        new
                        {
                            Id = 20,
                            AddedByUserId = "00000000-0000-0000-0000-000000000000",
                            DateAdded = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A jazz musician and an aspiring actress fall in love.",
                            ImagePath = "/images/movies/lalaland.jpg",
                            Name = "La La Land",
                            Source = "UserImport"
                        });
                });

            modelBuilder.Entity("favflicks.data.Models.MovieRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("MovieRatings");
                });

            modelBuilder.Entity("favflicks.data.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("favflicks.data.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sci-Fi"
                        });
                });

            modelBuilder.Entity("favflicks.data.Models.UserList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserList");
                });

            modelBuilder.Entity("favflicks.data.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfile");
                });

            modelBuilder.Entity("favflicks.data.Models.WatchList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("WatchList");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("favflicks.data.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("favflicks.data.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("favflicks.data.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("favflicks.data.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieTag", b =>
                {
                    b.HasOne("favflicks.data.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("favflicks.data.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("favflicks.data.Models.Comment", b =>
                {
                    b.HasOne("favflicks.data.Models.Movie", "Movie")
                        .WithMany("Comments")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("favflicks.data.Models.AppUser", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("favflicks.data.Models.Favorite", b =>
                {
                    b.HasOne("favflicks.data.Models.Movie", "Movie")
                        .WithMany("Favorites")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("favflicks.data.Models.AppUser", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("favflicks.data.Models.ListMovie", b =>
                {
                    b.HasOne("favflicks.data.Models.Movie", "Movie")
                        .WithMany("ListMovies")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("favflicks.data.Models.UserList", "UserList")
                        .WithMany("ListMovies")
                        .HasForeignKey("UserListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("UserList");
                });

            modelBuilder.Entity("favflicks.data.Models.Movie", b =>
                {
                    b.HasOne("favflicks.data.Models.AppUser", "AddedByUser")
                        .WithMany("Movies")
                        .HasForeignKey("AddedByUserId");

                    b.Navigation("AddedByUser");
                });

            modelBuilder.Entity("favflicks.data.Models.MovieRating", b =>
                {
                    b.HasOne("favflicks.data.Models.Movie", "Movie")
                        .WithMany("Ratings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("favflicks.data.Models.AppUser", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("favflicks.data.Models.Review", b =>
                {
                    b.HasOne("favflicks.data.Models.Movie", "Movie")
                        .WithMany("Reviews")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("favflicks.data.Models.AppUser", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("favflicks.data.Models.UserList", b =>
                {
                    b.HasOne("favflicks.data.Models.AppUser", "User")
                        .WithMany("Lists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("favflicks.data.Models.UserProfile", b =>
                {
                    b.HasOne("favflicks.data.Models.AppUser", "User")
                        .WithOne("Profile")
                        .HasForeignKey("favflicks.data.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("favflicks.data.Models.WatchList", b =>
                {
                    b.HasOne("favflicks.data.Models.Movie", "Movie")
                        .WithMany("Watchlists")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("favflicks.data.Models.AppUser", "User")
                        .WithMany("watchLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("favflicks.data.Models.AppUser", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Favorites");

                    b.Navigation("Lists");

                    b.Navigation("Movies");

                    b.Navigation("Profile");

                    b.Navigation("Ratings");

                    b.Navigation("Reviews");

                    b.Navigation("watchLists");
                });

            modelBuilder.Entity("favflicks.data.Models.Movie", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Favorites");

                    b.Navigation("ListMovies");

                    b.Navigation("Ratings");

                    b.Navigation("Reviews");

                    b.Navigation("Watchlists");
                });

            modelBuilder.Entity("favflicks.data.Models.UserList", b =>
                {
                    b.Navigation("ListMovies");
                });
#pragma warning restore 612, 618
        }
    }
}
